pkg/iscsi/iscsi.go, pkg/iscsi/iscsi_util.go
=> Correct/use better struct fields/variables in iscsi driver

Gopkg.lock, pkg/iscsi/iscsi.go, pkg/iscsi/iscsi_util.go, vendor/github.com/kubernetes-csi/csi-lib-iscsi/LICENSE, vendor/github.com/kubernetes-csi/csi-lib-iscsi/iscsi/iscsi.go, vendor/github.com/kubernetes-csi/csi-lib-iscsi/iscsi/iscsiadm.go
/kind cleanup
This PR just change csi-driver-iscsi to use csi-lib-iscsi, without any interface changes to users.
Fixes #5
@j-griffith
I agree to eventually add locking and more error handling, but let's start just replacing with the library, to make review easier. Also, I think that we should put persist files in staging path, not publish path(as current code do), later. 
```release-note
NONE
```
=> Use csi-lib-iscsi

pkg/iscsi/iscsi.go, pkg/iscsi/iscsi_util.go
=> Rename iscsi_lib to iscsiLib to avoid snake case import

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/support.md, .github/workflows/darwin.yaml, .github/workflows/linux.yaml
/kind documentation
doc: add issue template and also add darwin and golint tests
Fixes #
```release-note
none
```
=> doc: add issue template

pkg/iscsi/controllerserver.go, pkg/iscsi/iscsi.go, pkg/iscsi/iscsi_util.go, pkg/iscsi/server.go
this commit address unhandled error returns and also correct
duplicated conversion of a type along with other linter fixes
-->
```release-note-none
```
=> address error return and unwanted type conversion

README.md, SECURITY_CONTACTS, pkg/iscsi/driver.go
This commit update the readme with the driver version available
in the deploy directory along with some other markdown corrections
in the same file.
-->
```release-note
NONE
```
=> doc: update plugin version in the readme

docs/csi-debug.md
=> Add more debugging tips to the documentation

pkg/iscsi/driver.go, pkg/iscsi/identityserver.go, pkg/iscsi/iscsi.go, pkg/iscsi/iscsi_util.go, pkg/iscsi/nodeserver.go, pkg/lib/iscsi/iscsi/iscsi.go, vendor/github.com/kubernetes-csi/csi-lib-iscsi/iscsi/iscsi.go
=> code cleanup and formatting corrections in iscsi package.

pkg/iscsi/driver.go, pkg/iscsi/identityserver.go, pkg/iscsi/iscsi.go, pkg/iscsi/iscsi_util.go, pkg/iscsi/nodeserver.go, pkg/iscsi/server.go
=> iscsi: correct error message format

.github/workflows/trivy.yaml, Dockerfile, Makefile
/kind bug
fix: CVE-2021-3997 in image build, fixed following image CVE:
https://github.com/kubernetes-csi/csi-driver-iscsi/runs/4810456604?check_suite_focus=true
```
test/iscsi-csi:latest (ubuntu 20.04)
====================================
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 0, CRITICAL: 0)
+-------------+------------------+----------+-------------------+-------------------+--------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |   FIXED VERSION   |                TITLE                 |
+-------------+------------------+----------+-------------------+-------------------+--------------------------------------+
| libsystemd0 | CVE-2021-3997    | MEDIUM   | …
```
=> fix: CVE-2021-3997 in image build

.gitattributes, .github/workflows/golangci-lint.yml, cmd/iscsiplugin/main.go, pkg/iscsi/driver.go, pkg/iscsi/server.go
Fix https://github.com/kubernetes-csi/csi-driver-iscsi/issues/72
-->
```release-note
NONE
```
=> Enable golang-ci linter in the project

.github/workflows/codespell.yml, .github/workflows/golangci-lint.yml, .github/workflows/shellcheck.yaml, .prow.sh, Dockerfile, Makefile, iscsiplugin.sh, pkg/iscsi/driver.go, pkg/lib/iscsi/iscsi/multipath.go, release-tools/SIDECAR_RELEASE_PROCESS.md, release-tools/prow.sh, vendor/github.com/kubernetes-csi/csi-lib-iscsi/iscsi/multipath.go
This PR covers below:
```release-note
NONE
```
=> Fix CVEs, add Make targets, update linters

README.md
=> Add compatibility matrix, release..etc to the README

Dockerfile, pkg/iscsi/iscsi.go, pkg/iscsi/iscsi_util.go
/kind bug
fix: driver pod crash when portals are not provided
Fixes #
```release-note
fix: driver pod crash when portals are not provided
```
=> fix: driver pod crash when portals are not provided

.github/workflows/golangci-lint.yml, hack/verify-spelling.sh, release-tools/prow.sh, release-tools/verify-spelling.sh
Squashed 'release-tools/' changes from 335339f0..37d11049
[37d11049](https://github.com/kubernetes-csi/csi-release-tools/commit/37d11049) Merge [pull request #191](https://github.com/kubernetes-csi/csi-release-tools/pull/191) from pohly/go-1.18
[db917f5c](https://github.com/kubernetes-csi/csi-release-tools/commit/db917f5c) update to Go 1.18
git-subtree-dir: release-tools
git-subtree-split: 37d1104926b30aa0544abb5a16c980ba82aaa585
```release-note
NONE
```
=> master: update release-tools

Dockerfile
/kind bug
fix: CVE issues by patching packages
Fixes #
```release-note
fix: CVE issues by patching packages
```
=> fix: CVE issues by patching packages

Dockerfile, deploy/csi-iscsi-node.yaml
This commit change the registry path of the plugin image from k8s.gcr.io
to registry.k8s.io
Refer# https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
```release-note
NONE
```
=> chore: change the registry path to registry.k8s.io

.github/dependabot.yaml
Automatically updating dependencies saves on manual labor. The PRs created by
the bot are also more informative.
k8s.io packages are excluded. At least the staging repos don't have API
stability guarantees and better should get updated manually.
This is pretty much copy of csi-test PR here https://github.com/kubernetes-csi/csi-test/pull/365
```release-note
none
```
=> GitHub: enable dependabot

.github/workflows/trivy.yaml, Makefile, go.mod, go.sum, vendor/golang.org/x/net/context/go17.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/hpack/encode.go, vendor/golang.org/x/net/http2/hpack/hpack.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/modules.txt
at present the makefile holds a target to make the container
which is used by github actions like trivvy and also from the
release process. This commit add the container only for testing
and leaving rest of the process to the release tools.
This PR also fix an important CVE on `golang.org/x/net` package
```release-note
NONE
```
=> remove explicit  `make container` target

deploy/csi-iscsi-node.yaml
/kind bug
fix: set ClusterFirstWithHostNet as default dnsPolicy
This PR also fixed a bug that controller should also set `hostNetwork: true`.
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
"ClusterFirstWithHostNet": For Pods running with hostNetwork, you should explicitly set its DNS policy to "ClusterFirstWithHostNet". Otherwise, Pods running with hostNetwork and "ClusterFirst" will fallback to the behavior of the "Default" policy.
Note: This is not supported on Windows. See [below](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#dns-windows) for details
Fixes #600
**Requirements**: …
=> fix: set ClusterFirstWithHostNet as default dnsPolicy

pkg/iscsi/iscsi_util.go
cleanup:change the error log when disconnecting volume
Fixes #
```release-note
cleanup:change the error log when disconnecting volume
```
=> cleanup:change the error log when disconnecting volume

.github/workflows/golangci-lint.yml, pkg/iscsilib/iscsi.go
* golang version is 1.19 and go.mod is 1.22
* 1.51 golang-lint was compiled with too old a version of go
* exportloopref no long relevant using copyloopref instead
* Fixed new lint issue
```release-note
NONE```
=> chore: update golang lint workflow

pkg/iscsilib/iscsi.go
/kind cleanup
This usage has been deprecated since 1.16.
```release-note
none
```
=> chore: fix deprecated import
