kubernetes-csi/csi-driver-iscsi

- .cloudbuild.sh
- cloudbuild.yaml
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
**What this PR does / why we need it**: The Prow job fails due to missing cloudbuild.yaml
Fixes #
```release-note
NONE  
```
> Add cloudbuild.yaml for Prow

- README.md
> correct csc execution section

- kubernetes/csi-attacher-iscsiplugin.yaml
- kubernetes/csi-nodeplugin-iscsiplugin.yaml
update apiVersion of statefulset to v1 from 1beta1 and Daemonsets to v1 from  apps/v1beta2
> update apiVersion of statefulset to v1 and Daemonsets to v1

- docs/csi-debug.md
This commit adds details about how to debug, update and watch
logs of iscsi csi driver.
-->
```release-note
NONE
```
> Add details about the debugging of the driver

- .github/workflows/pluto.yaml
/kind cleanup
test: add api version verification
Fixes #
```release-note
none
```
> test: add api version verification

- Makefile
test: fix sanity test failure
Fixes #
```release-note
none
```
> test: fix sanity test failure

- Dockerfile
/kind cleanup
cleanup: remove unnecessary CVE packages
Fixes #
```release-note
none
```
> cleanup: remove unnecessary CVE packages

- README.md
The image reference in the readme was not correct and this commit
address the same
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
Fixes #
```release-note
```
> chore: correct the image repo reference in the readme

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- deploy/uninstall-driver.sh
- docs/csi-dev.md
- docs/install-csi-driver-master.md
- docs/install-iscsi-csi-driver.md
/kind documentation
doc: refine driver docs
Fixes #
```release-note
none
```
> doc: refine driver docs

- CONTRIBUTING.md
- README.md
- RELEASE.md
- code-of-conduct.md
/kind cleanup
-->
```release-note
NONE
```
> doc: correcting markdown formatting errors on readme

- docs/csi-dev.md
- docs/install-csi-driver-master.md
- docs/install-iscsi-csi-driver.md
- examples/storageclass.yaml
> Example yaml and documentation correction

- .github/workflows/darwin.yaml
- .github/workflows/linux.yaml
- .github/workflows/pluto.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/trivy.yaml
- .github/workflows/windows.yaml
> Corrections in github action yamls.

- .github/workflows/codespell.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/linux.yaml
- pkg/lib/iscsi/OWNERS
- pkg/lib/iscsi/iscsi/iscsi.go
- pkg/lib/iscsi/iscsi/iscsiadm.go
- pkg/lib/iscsi/iscsi/multipath.go
- vendor/github.com/kubernetes-csi/csi-lib-iscsi/iscsi/iscsi.go
- vendor/github.com/kubernetes-csi/csi-lib-iscsi/iscsi/iscsiadm.go
- vendor/github.com/kubernetes-csi/csi-lib-iscsi/iscsi/multipath.go
Depends # https://github.com/kubernetes-csi/csi-lib-iscsi/pull/38
```release-note
none
```
> make iscsi library in sync 

- Dockerfile
/kind cleanup
Update the base image to the latest release.
None
None
```release-note
None
```
> Update debian-base image to v1.4.3

- examples/pod.yaml
- examples/pv.yaml
- pkg/iscsi/iscsi.go
/kind bug
fix: CHAPDiscovery issue
original `DoCHAPDiscovery` value is not passed to connector, this PR fixes the issue.
Fixes #
```release-note
fix: CHAPDiscovery issue
```
> fix: CHAPDiscovery issue

- Dockerfile
/kind feature
chore: upgrade base image to debian-base: bookworm
Fixes #
```release-note
none
```
> chore: upgrade base image to debian-base: bookworm

- release-tools/KUBERNETES_CSI_OWNERS_ALIASES
- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/generate_patch_release_notes.sh
- release-tools/go-modules-update.sh
- release-tools/prow.sh
- release-tools/pull-test.sh
/kind cleanup
Update release tools
Fixes #
```release-note
none
```
> Update release tools

- .github/workflows/trivy.yaml
- release-tools/SIDECAR_RELEASE_PROCESS.md
- release-tools/generate-patch-release-notes.sh
test: fix trivy action failure
Fixes #
```release-note
none
```
> test: fix trivy action failure

- .github/workflows/trivy.yaml
- go.mod
chore: fix trivy github action errror
Fixes #
```release-note
none
```
> chore: fix trivy github action errror

- Dockerfile
/kind feature
chore: upgrade base image to bookworm:v1.0.4
Fixes #
```release-note
none
```
> chore: upgrade base image to bookworm:v1.0.4

- .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
Avoid the need to change 'none' to 'NONE' to follow the directions.
```release-note
NONE
```
> chore: update pull request template release notes

- .github/dependabot.yaml
/kind cleanup
cleanup: remove group update in dependabot
Fixes #
```release-note
none
```
> cleanup: remove group update in dependabot

- go.mod
- go.sum
- vendor/modules.txt
/kind bug
fix: CVE-2024-45338
Fixes #
**Release note**:
```release-note
fix: CVE-2024-45338
```
> fix: CVE-2024-45338

- release-tools/cloudbuild.yaml
- release-tools/prow.sh
/kind cleanup
chore: Update csi release tools
```
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
```
Fixes #
**Requirements**:
**Release note**:
```
none
```
> chore: Update csi release tools 

- .github/workflows/golangci-lint.yml
- go.mod
- release-tools/prow.sh
/kind cleanup
chore: use go1.24
Fixes #
```release-note
NONE
```
> chore: use go1.24

- .github/workflows/trivy.yaml
test: fix CVE-2025-4673 in trivy action
Fixes #
```release-note
NONE
```
> test: fix CVE-2025-4673 in trivy action

- .github/workflows/golangci-lint.yml
- pkg/iscsi/iscsi.go
- pkg/iscsi/utils.go
- pkg/iscsilib/iscsi.go
- pkg/iscsilib/iscsiadm.go
/kind cleanup
Update golangci-lint to v8
Fixes: https://github.com/kubernetes-csi/csi-driver-iscsi/pull/340
```release-note
NONE
```
> chore: update golangci-lint to v8

- .github/workflows/trivy.yaml
test: fix CVE-2025-47907 traivy test failure
Fixes #
**Requirements**:
**Release note**:
```
none
```
> test: fix CVE-2025-47907 traivy test failure
